modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "create_farming_essentials"
version = "${version}"
displayName = "Create Farming Essentials"
authors = "alexzander700"
description = '''
Create: Farming Essentials is a mod that adds Farming Essentials such as Sprinklers and Trellises
'''
#logoFile = ""

[[dependencies.create_farming_essentials]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_farming_essentials]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_farming_essentials]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_farming_essentials]]
modId = "create"
type = "required"
versionRange = "[6.0.10,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "create_farming_essentials.mixins.json"

[[mixins]]
config = "create_farming_essentials.neoforge.mixins.json"
